#
# Module manifest for module 'PoshBot.XKCD'
#
# Generated by: Brandon Olin
#
# Generated on: 3/20/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PoshBot.XKCD.psm1'

# Version number of this module.
ModuleVersion = '1.2.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '9409249d-0faa-4636-b882-22d766369f02'

# Author of this module
Author = 'Brandon Olin'

# Company or vendor of this module
CompanyName = 'Community'

# Copyright statement for this module
Copyright = '(c) 2017 Brandon Olin. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PoshBot module for retrieving XKCD comics'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('PoshBot')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Get-XKCD')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('XKCD', 'PoshBot', 'ChatOps', 'Comic')

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/poshbotio/PoshBot.XKCD/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/poshbotio/PoshBot.XKCD'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
## 1.1.1 - 2017-09-14
### Fixed
- Ensure TLS 1.2 is used with calling XKCD API (via @DunlapOverbelt).

## [1.1.0] - 2017-07-25
### Added
- Add -AltText switch parameter.
    When set, the function will emit Alt Text (formatted as quote via markdown) for each comic image output. (via @alexsalisbury)

## [1.0.2] - 2017-07-12
### Fixed
- Add PoshBot dependency to module manifest.

## [1.0.1] - 2017-03-24
### Changed
- Explicitly export function in module manifest
- Renamed function to conform to PowerShell conventions (verb-noun) and set bot command name to "xkcd" via [PoshBot.BotCommand()] attribute.

## [1.0.0] - 2017-03-21
### Added
- Initial commit
'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

